CollectibleCardsTradingShopProject/Models/Card.cs
namespace CollectibleCardsTradingShopProject.Models
{
    public class Card
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Image { get; set; } = null!;
        public int FranchiseId { get; set; }
        public int RarityId { get; set; }        
        public virtual Rarity? Rarity { get; set; }
        public virtual Franchise? Franchise { get; set; }
        public virtual ICollection<CardInLot> CardInLots { get; set; } = new List<CardInLot>();
        public virtual ICollection<UserCard> UserCards { get; set; } = new List<UserCard>();
    }
}

CollectibleCardsTradingShopProject/ViewModels/CardsViewModel.cs
using CollectibleCardsTradingShopProject.Models;

namespace CollectibleCardsTradingShopProject.ViewModels
{
    public class CardsViewModel
    {
        public IEnumerable<Card> Cards { get; set; } = new List<Card>();
        public string Franchise { get; set; } = null!;
        public string Rarity { get; set; } = null!;
        public PageViewModel PageViewModel { get; set; } = null!;
        public SortViewModel SortViewModel { get; set; } = null!;
    }
}

CollectibleCardsTradingShopProject/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CollectibleCardsTradingShopProject.Data;
using CollectibleCardsTradingShopProject.Models;
using CollectibleCardsTradingShopProject.ViewModels;
using Microsoft.Data.SqlClient;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Authorization;

namespace CollectibleCardsTradingShopProject.Controllers
{
    public class CardsController : Controller
    {
        private readonly int pageSize = 50;

        private readonly ApplicationDbContext _context;

        public CardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cards
        public async Task<IActionResult> Index(string Franchise = "", string Name = "", SortState sortOrder = SortState.No, int page = 1)
        {
            IQueryable<Card> cardsContext = _context.Cards
                .Include(c => c.Franchise)
                .Include(c => c.Rarity);

            cardsContext = SortSearch(cardsContext, sortOrder, Franchise ?? "", Name ?? "");

            var count = await cardsContext.CountAsync();

            var cards = await cardsContext
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            CardsViewModel cardsViewModel = new()
            {
                Cards = cards,
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortViewModel(sortOrder),
                Franchise = Franchise
            };

            return View(cardsViewModel);
        }
        private IQueryable<Card> SortSearch(IQueryable<Card> cardsContext, SortState sortOrder, string FranchiseForFilter, string Name)
        {
            switch (sortOrder)
            {
                case SortState.FranchiseAsc:
                    cardsContext = cardsContext.OrderBy(s => s.Franchise.Name);
                    break;
                case SortState.FranchiseDesc:
                    cardsContext = cardsContext.OrderByDescending(s => s.Franchise.Name);
                    break;
                case SortState.RarityAsc:
                    cardsContext = cardsContext.OrderBy(s => s.Rarity.Id);
                    break;
                case SortState.RarityDesc:
                    cardsContext = cardsContext.OrderByDescending(s => s.Rarity.Id);
                    break;
                case SortState.NameAsc:
                    cardsContext = cardsContext.OrderBy(s => s.Name);
                    break;
                case SortState.NameDesc:
                    cardsContext = cardsContext.OrderByDescending(s => s.Name);
                    break;
            }
            if (FranchiseForFilter != "")
            {
                //cardsContext = cardsContext.Where(o => o.Franchise.Name.Contains(FranchiseForFilter ?? ""));
                cardsContext = cardsContext.Where(c => c.Franchise.Name == FranchiseForFilter);
            }
            if (Name != "")
            {
                cardsContext = cardsContext.Where(c => c.Name == Name);
            }
            return cardsContext;
        }

        // GET: Cards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Cards
                .Include(c => c.Franchise)
                .Include(c => c.Rarity)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // GET: Cards/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["FranchiseId"] = new SelectList(_context.Franchises, "Id", "Name");
            ViewData["RarityId"] = new SelectList(_context.Rarities, "Id", "Name");
            return View();
        }

        // POST: Cards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Image,FranchiseId,RarityId")] Card card)
        {
            if (ModelState.IsValid)
            {
                _context.Add(card);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FranchiseId"] = new SelectList(_context.Franchises, "Id", "Id", card.FranchiseId);
            ViewData["RarityId"] = new SelectList(_context.Rarities, "Id", "Id", card.RarityId);
            return View(card);
        }

        // GET: Cards/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Cards.FindAsync(id);
            if (card == null)
            {
                return NotFound();
            }
            ViewData["FranchiseId"] = new SelectList(_context.Franchises, "Id", "Name", card.FranchiseId);
            ViewData["RarityId"] = new SelectList(_context.Rarities, "Id", "Name", card.RarityId);
            return View(card);
        }

        // POST: Cards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image,FranchiseId,RarityId")] Card card)
        {
            if (id != card.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(card);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CardExists(card.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FranchiseId"] = new SelectList(_context.Franchises, "Id", "Id", card.FranchiseId);
            ViewData["RarityId"] = new SelectList(_context.Rarities, "Id", "Id", card.RarityId);
            return View(card);
        }

        // GET: Cards/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var card = await _context.Cards
                .Include(c => c.Franchise)
                .Include(c => c.Rarity)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (card == null)
            {
                return NotFound();
            }

            return View(card);
        }

        // POST: Cards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var card = await _context.Cards.FindAsync(id);
            if (card != null)
            {
                _context.Cards.Remove(card);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CardExists(int id)
        {
            return _context.Cards.Any(e => e.Id == id);
        }
    }
}

CollectibleCardsTradingShopProject/Views/Cards/Create.cshtml
@model CollectibleCardsTradingShopProject.Models.Card

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FranchiseId" class="control-label"></label>
                <select asp-for="FranchiseId" class ="form-control" asp-items="ViewBag.FranchiseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="RarityId" class="control-label"></label>
                <select asp-for="RarityId" class ="form-control" asp-items="ViewBag.RarityId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollectibleCardsTradingShopProject/Views/Cards/Delete.cshtml
@model CollectibleCardsTradingShopProject.Models.Card

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rarity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rarity.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Franchise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Franchise.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CollectibleCardsTradingShopProject/Views/Cards/Details.cshtml
@model CollectibleCardsTradingShopProject.Models.Card

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rarity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rarity.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Franchise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Franchise.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CollectibleCardsTradingShopProject/Views/Cards/Edit.cshtml
@model CollectibleCardsTradingShopProject.Models.Card

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Card</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FranchiseId" class="control-label"></label>
                <select asp-for="FranchiseId" class="form-control" asp-items="ViewBag.FranchiseId"></select>
                <span asp-validation-for="FranchiseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RarityId" class="control-label"></label>
                <select asp-for="RarityId" class="form-control" asp-items="ViewBag.RarityId"></select>
                <span asp-validation-for="RarityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CollectibleCardsTradingShopProject/Views/Cards/Index.cshtml
@model CollectibleCardsTradingShopProject.ViewModels.CardsViewModel;
@using CollectibleCardsTradingShopProject.ViewModels;
@{
    ViewData["Title"] = "Index";
    var sortModel = ViewData["SortModel"] as CollectibleCardsTradingShopProject.ViewModels.SortViewModel;
}

<h1>Index</h1>

@using (Html.BeginForm("Index", "Cards", FormMethod.Get, new { @class = "mb-3" }))
{
            <div class="row">
                <div class="col-md-4">
            @Html.TextBox("franchise", Model.Franchise, new { @class = "form-control", placeholder = "Franchise Name" })
                </div>
                <div class="col-md-4">
            @Html.TextBox("name", "", new { @class = "form-control", placeholder = "Card Name" })
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary">Filter</button>
                    <a asp-action="Index" class="btn btn-secondary">Reset</a>
                </div>
            </div>
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" 
                   asp-route-sortOrder="@(Model.SortViewModel.CurrentState == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc)" 
                   asp-route-page="@Model.PageViewModel.PageNumber" 
                   asp-route-franchise="@Model.Franchise">
                    Name
                    @if (Model.SortViewModel.CurrentState == SortState.NameAsc)
                    {
                                <span>&uarr;</span>
                    }
                    else if (Model.SortViewModel.CurrentState == SortState.NameDesc)
                    {
                                <span>&darr;</span>
                    }
                </a>
            </th>
            <th>Image</th>
            <th>
                <a asp-action="Index" 
                   asp-route-sortOrder="@(Model.SortViewModel.CurrentState == SortState.FranchiseAsc ? SortState.FranchiseDesc : SortState.FranchiseAsc)" 
                   asp-route-page="@Model.PageViewModel.PageNumber" 
                   asp-route-franchise="@Model.Franchise">
                    Franchise
                    @if (Model.SortViewModel.CurrentState == SortState.FranchiseAsc)
                    {
                                <span>&uarr;</span>
                    }
                    else if (Model.SortViewModel.CurrentState == SortState.FranchiseDesc)
                    {
                                <span>&darr;</span>
                    }
                </a>
            </th>
            <th>
                <a asp-action="Index" 
                   asp-route-sortOrder="@(Model.SortViewModel.CurrentState == SortState.RarityAsc ? SortState.RarityDesc : SortState.RarityAsc)" 
                   asp-route-page="@Model.PageViewModel.PageNumber" 
                   asp-route-franchise="@Model.Franchise">
                    Rarity
                    @if (Model.SortViewModel.CurrentState == SortState.RarityAsc)
                    {
                                <span>&uarr;</span>
                    }
                    else if (Model.SortViewModel.CurrentState == SortState.RarityDesc)
                    {
                                <span>&darr;</span>
                    }
                </a>
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cards)
        {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>
                            <img src="@item.Image" alt="@item.Name" style="width:100px; height:auto;" />
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Franchise.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Rarity.Name)</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
        }
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.PageViewModel.HasPreviousPage)
        {
                        <li class="page-item">
                            <a class="page-link" asp-action="Index" 
                               asp-route-page="@(Model.PageViewModel.PageNumber - 1)" 
                               asp-route-franchise="@Model.Franchise" 
                               asp-route-sortOrder="@(Model.SortViewModel.CurrentState)">
                                Previous
                            </a>
                        </li>
        }

        <li class="page-item @(1 == Model.PageViewModel.PageNumber ? "active" : "")">
            <a class="page-link" asp-action="Index" 
               asp-route-page="1" 
               asp-route-franchise="@Model.Franchise" 
               asp-route-sortOrder="@(Model.SortViewModel.CurrentState)">
                1
            </a>
        </li>

        @if (Model.PageViewModel.PageNumber > 3)
        {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
        }

        @for (int i = Math.Max(2, Model.PageViewModel.PageNumber - 1);
          i <= Math.Min(Model.PageViewModel.TotalPages - 1, Model.PageViewModel.PageNumber + 1);
          i++)
        {
                        <li class="page-item @(i == Model.PageViewModel.PageNumber ? "active" : "")">
                            <a class="page-link" asp-action="Index" 
                               asp-route-page="@i" 
                               asp-route-franchise="@Model.Franchise" 
                               asp-route-sortOrder="@(Model.SortViewModel.CurrentState)">
                    @i
                            </a>
                        </li>
        }

        @if (Model.PageViewModel.PageNumber < Model.PageViewModel.TotalPages - 2)
        {
                        <li class="page-item disabled"><span class="page-link">...</span></li>
        }

        <li class="page-item @(Model.PageViewModel.TotalPages == Model.PageViewModel.PageNumber ? "active" : "")">
            <a class="page-link" asp-action="Index" 
               asp-route-page="@Model.PageViewModel.TotalPages" 
               asp-route-franchise="@Model.Franchise" 
               asp-route-sortOrder="@(Model.SortViewModel.CurrentState)">
                @Model.PageViewModel.TotalPages
            </a>
        </li>

        @if (Model.PageViewModel.HasNextPage)
        {
                        <li class="page-item">
                            <a class="page-link" asp-action="Index" 
                               asp-route-page="@(Model.PageViewModel.PageNumber + 1)" 
                               asp-route-franchise="@Model.Franchise" 
                               asp-route-sortOrder="@(Model.SortViewModel.CurrentState)">
                                Next
                            </a>
                        </li>
        }
    </ul>

    <form method="get" class="d-inline-block" style="margin-left: 10px;">
        <input type="hidden" name="franchise" value="@Model.Franchise" />
        <input type="hidden" name="sortOrder" value="@(Model.SortViewModel.CurrentState)" />
        <div class="input-group">
            <input type="number" name="page" class="form-control" 
                   placeholder="Page" 
                   min="1" 
                   max="@Model.PageViewModel.TotalPages" 
                   value="@Model.PageViewModel.PageNumber" />
            <button type="submit" class="btn btn-primary">Go</button>
        </div>
    </form>
</nav>